#!/usr/bin/env bash
# Akalynth Dev Deploy — ops-dev-01 (194.147.221.89)
#
# Thin wrapper around deploy_beta.sh that pre-sets the dev lane env vars.
# Run from the repo root on ops-dev-01:
#
#   ./infra/deploy_dev.sh [tag|branch]
#   ./infra/deploy_dev.sh main
#
# Health is probed at https://beta-api.akalynth.com/v1/health after deploy.
# Override with AKALYNTH_HEALTH_URL if needed.
#
# Chronicle key: the dev box uses ~/dev/akalynth/apps/server/chronicle.key
# (generated by `npm run dev:bootstrap` on first run). Production keys live in
# /etc/akalynth/ and are never used here.
#
# Exit codes mirror deploy_beta.sh:
#   0  deploy + health check passed
#   1  health check failed (rollback attempted)
#   2+ build / git failure

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Dev-lane overrides ────────────────────────────────────────────────────────

# Health probe hits the beta subdomain.
export AKALYNTH_HEALTH_URL="${AKALYNTH_HEALTH_URL:-https://beta-api.akalynth.com/v1/health}"

# Dev key lives alongside the server source (gitignored, generated by dev:bootstrap).
# deploy_beta.sh does not manage key creation; run `npm run dev:bootstrap` first if the
# key is absent.
export CHRONICLE_KEY_PATH="${CHRONICLE_KEY_PATH:-apps/server/chronicle.key}"

# Allow plain HTTP loopback (no TLS between Caddy and Node on this box).
export ALLOW_INSECURE_LOCAL="${ALLOW_INSECURE_LOCAL:-1}"

# ── Delegate to the canonical deploy script ───────────────────────────────────
echo "[deploy_dev] lane=dev health=${AKALYNTH_HEALTH_URL}"
exec "${SCRIPT_DIR}/deploy_beta.sh" "$@"
