package com.akalynth.client.actions

import com.akalynth.client.chronicle.ChronicleStore
import com.akalynth.client.ui.components.character.CharacterSex
import com.akalynth.client.ui.components.hotbar.ItemRarity

/**
 * Single ingress for player actions.
 *
 * Responsibilities:
 * 1. Generate actionId for correlation
 * 2. Create pending ChronicleEvent (for actions that show in chronicle)
 * 3. Forward intent to transport (network layer)
 *
 * UI calls dispatchX() methods, NOT constructors.
 * This ensures:
 * - actionId is always generated by bus
 * - pending events are always created before transport
 * - single point of control for action flow
 *
 * Wiring boundary:
 * - UI should NOT call ActionBus directly from composables
 * - Route through ViewModel to prevent recomposition double-sends
 */
class ActionBus(
    private val ids: ActionIdGenerator = UuidActionIdGenerator(),
    private val chronicle: ChronicleStore,
    private val transport: ActionTransport,
    private val clock: Clock = SystemClock
) {
    /** Current player zone (updated by game state) */
    var zone: String? = null

    /** Current player X coordinate */
    var x: Int? = null

    /** Current player Y coordinate */
    var y: Int? = null

    /**
     * Dispatch an attack action.
     *
     * @param targetId Optional target entity ID
     * @return The stamped action intent
     */
    suspend fun dispatchAttack(targetId: String? = null): ActionIntent.Attack {
        val intent = ActionIntent.Attack(
            actionId = ids.nextId(),
            targetId = targetId
        )
        return dispatch(intent)
    }

    /**
     * Dispatch a use hotbar slot action.
     *
     * @param slotIndex Hotbar slot index (0-3)
     * @param itemId Item ID being used
     * @return The stamped action intent
     */
    suspend fun dispatchUseHotbarSlot(slotIndex: Int, itemId: String): ActionIntent.UseHotbarSlot {
        val intent = ActionIntent.UseHotbarSlot(
            actionId = ids.nextId(),
            slotIndex = slotIndex,
            itemId = itemId
        )
        return dispatch(intent)
    }

    /**
     * Dispatch a drop hotbar slot action.
     *
     * @param slotIndex Hotbar slot index (0-3)
     * @param itemId Item ID being dropped
     * @param itemName Display name of item
     * @param rarity Item rarity (for chronicle display)
     * @return The stamped action intent
     */
    suspend fun dispatchDropHotbarSlot(
        slotIndex: Int,
        itemId: String,
        itemName: String,
        rarity: ItemRarity
    ): ActionIntent.DropHotbarSlot {
        val intent = ActionIntent.DropHotbarSlot(
            actionId = ids.nextId(),
            slotIndex = slotIndex,
            itemId = itemId,
            itemName = itemName,
            rarity = rarity
        )
        return dispatch(intent)
    }

    /**
     * Dispatch a pickup item action.
     *
     * @param itemId Item ID being picked up
     * @param itemName Display name of item
     * @param x X coordinate of item
     * @param y Y coordinate of item
     * @return The stamped action intent
     */
    suspend fun dispatchPickupItem(
        itemId: String,
        itemName: String,
        x: Int,
        y: Int
    ): ActionIntent.PickupItem {
        val intent = ActionIntent.PickupItem(
            actionId = ids.nextId(),
            itemId = itemId,
            itemName = itemName,
            x = x,
            y = y
        )
        return dispatch(intent)
    }

    /**
     * Dispatch a create character action.
     *
     * @param name Character name
     * @param sex Character sex
     * @return The stamped action intent
     */
    suspend fun dispatchCreateCharacter(
        name: String,
        sex: CharacterSex
    ): ActionIntent.CreateCharacter {
        val intent = ActionIntent.CreateCharacter(
            actionId = ids.nextId(),
            name = name,
            sex = sex
        )
        return dispatch(intent)
    }

    /**
     * Dispatch a world-event contribution intent.
     *
     * The server is the only authority for event phase/progress; this sends
     * only an existing use_skill-style intent and creates no pending event.
     */
    suspend fun dispatchWorldEventContribution(
        eventId: String,
        contributionId: String
    ): ActionIntent.WorldEventContribution {
        val intent = ActionIntent.WorldEventContribution(
            actionId = ids.nextId(),
            eventId = eventId,
            contributionId = contributionId
        )
        return dispatch(intent)
    }

    /**
     * Update player position (call from game state sync).
     */
    fun updatePosition(zone: String?, x: Int?, y: Int?) {
        this.zone = zone
        this.x = x
        this.y = y
    }

    /**
     * Internal dispatch: creates pending event and forwards to transport.
     */
    private suspend fun <T : ActionIntent> dispatch(intent: T): T {
        // 1. Create pending chronicle event (if this action shows in chronicle)
        val pendingEvent = PendingEventMapper.map(intent, clock, zone, x, y)
        if (pendingEvent != null) {
            chronicle.upsert(pendingEvent)
        }

        // 2. Forward to transport (network)
        transport.send(intent)

        return intent
    }
}
