/**
 * Conformance Result Formatters
 *
 * Output formatters for conformance results.
 */
/**
 * Format result as human-readable text.
 */
export function formatResult(result) {
    const lines = [];
    // Header
    lines.push('═══════════════════════════════════════════════════════════════');
    lines.push(`  WLA CONFORMANCE REPORT`);
    lines.push('═══════════════════════════════════════════════════════════════');
    lines.push('');
    // Summary
    const status = result.conforms ? '✓ CONFORMANT' : '✗ NON-CONFORMANT';
    const statusIcon = result.conforms ? '✓' : '✗';
    lines.push(`Status:      ${status}`);
    lines.push(`Level:       Witness-${capitalize(result.level)}`);
    lines.push(`Passed:      ${result.passed}/${result.total}`);
    lines.push(`Failed:      ${result.failed}/${result.total}`);
    lines.push(`Timestamp:   ${new Date(result.timestamp_ms).toISOString()}`);
    lines.push('');
    // Violations (if any)
    if (result.violations.length > 0) {
        lines.push('─── VIOLATIONS ──────────────────────────────────────────────────');
        lines.push('');
        for (const v of result.violations) {
            lines.push(`  ✗ ${v.check_id} (RFC ${v.rfc_section})`);
            lines.push(`    ${v.message}`);
            if (v.remediation) {
                lines.push(`    → ${v.remediation}`);
            }
            lines.push('');
        }
    }
    // Warnings (if any)
    if (result.warnings.length > 0) {
        lines.push('─── WARNINGS ────────────────────────────────────────────────────');
        lines.push('');
        for (const w of result.warnings) {
            lines.push(`  ⚠ ${w}`);
        }
        lines.push('');
    }
    // Check details
    lines.push('─── CHECK RESULTS ───────────────────────────────────────────────');
    lines.push('');
    for (const check of result.checks) {
        const icon = check.passed ? '✓' : '✗';
        const req = check.requirement === 'MUST' ? '[MUST]' : check.requirement === 'SHOULD' ? '[SHOULD]' : '[MAY]';
        lines.push(`  ${icon} ${check.check_id} ${req}`);
        lines.push(`    ${check.description}`);
        if (!check.passed && check.error) {
            lines.push(`    Error: ${check.error}`);
        }
    }
    lines.push('');
    // Footer
    lines.push('═══════════════════════════════════════════════════════════════');
    lines.push(`  RFC WLA-001 | Witness-Ledger Architecture Conformance Suite`);
    lines.push('═══════════════════════════════════════════════════════════════');
    return lines.join('\n');
}
/**
 * Format result as JSON.
 */
export function formatResultJson(result) {
    return JSON.stringify(result, null, 2);
}
/**
 * Format result as Markdown.
 */
export function formatResultMarkdown(result) {
    const lines = [];
    // Title
    const status = result.conforms ? 'CONFORMANT' : 'NON-CONFORMANT';
    const emoji = result.conforms ? '✅' : '❌';
    lines.push(`# WLA Conformance Report`);
    lines.push('');
    lines.push(`**Status:** ${emoji} ${status}`);
    lines.push('');
    // Summary table
    lines.push('## Summary');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    lines.push(`| Level | Witness-${capitalize(result.level)} |`);
    lines.push(`| Passed | ${result.passed}/${result.total} |`);
    lines.push(`| Failed | ${result.failed}/${result.total} |`);
    lines.push(`| Timestamp | ${new Date(result.timestamp_ms).toISOString()} |`);
    lines.push('');
    // Violations
    if (result.violations.length > 0) {
        lines.push('## Violations');
        lines.push('');
        lines.push('| Check | RFC | Message |');
        lines.push('|-------|-----|---------|');
        for (const v of result.violations) {
            lines.push(`| ${v.check_id} | ${v.rfc_section} | ${v.message} |`);
        }
        lines.push('');
    }
    // All checks
    lines.push('## Check Results');
    lines.push('');
    const passed = result.checks.filter(c => c.passed);
    const failed = result.checks.filter(c => !c.passed);
    if (failed.length > 0) {
        lines.push('### Failed');
        lines.push('');
        for (const check of failed) {
            lines.push(`- ❌ **${check.check_id}** (${check.requirement})`);
            lines.push(`  - ${check.description}`);
            if (check.error) {
                lines.push(`  - Error: ${check.error}`);
            }
        }
        lines.push('');
    }
    if (passed.length > 0) {
        lines.push('### Passed');
        lines.push('');
        for (const check of passed) {
            lines.push(`- ✅ **${check.check_id}** - ${check.description}`);
        }
        lines.push('');
    }
    // Footer
    lines.push('---');
    lines.push('');
    lines.push('*Generated by WLA Conformance Suite (RFC WLA-001)*');
    return lines.join('\n');
}
/**
 * Capitalize first letter.
 */
function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
}
/**
 * Create a summary line for CI output.
 */
export function formatSummary(result) {
    const status = result.conforms ? 'PASS' : 'FAIL';
    return `[WLA-${result.level.toUpperCase()}] ${status}: ${result.passed}/${result.total} checks passed`;
}
